### ISSUE TITLE
Feature Request: Accept Outlook iCalendar emails

### ISSUE THREAD

**Issue by rmeske** [jpotts/share-inbound-invites#3]
Outlook has an option to send calendar invitations as an iCalendar when sent to an internet address.  This method does not attach an ics file rather it is encoded in the body of the email.

When received by Alfresco it is processed and 3 files are created.  One of them does not have an extension but it is the iCalendar event.  If it was saved during processing with an extension of ics it would then be processed properly as an iCalendar event.

**Comment by jpotts** [comment]
The issue is that Alfresco is not determining the mimetype properly. The code in its current state strictly checks the mimetype to see if it is text/calendar. If it isn't the attachment is skipped. I'll add a new configurable flag to specify whether the check should be strict, and if not, the code will attempt to parse any attachment with a mimetype of application/octet. This should cover the Outlook case.

**Comment by jpotts** [comment]
The problem with this approach is that if you have the flag set to be permissive and you send events from other systems that send both an ICS attachment and a multi part email, the code processes both (instead of just the ICS attachment) creating two entries.
